include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
    use_super_parameters: true
    always_use_package_imports: true
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_redundant_argument_values: true
    avoid_types_on_closure_parameters: true
    cascade_invocations: true
    combinators_ordering: true
    eol_at_end_of_file: true
    prefer_constructors_over_static_methods: true
    unawaited_futures: true
    unnecessary_lambdas: true
    unnecessary_underscores: true
    use_null_aware_elements: true
